version: "3.8"

networks:
    backend:
    frontend:

volumes:
    mariadb:
        driver: local
        driver_opts:
            type: none
            o: bind
            device: data/mariadb
    wordpress:
        driver: local
        driver_opts:
            type: none
            o: bind
            device: data/wordpress
    mariadb-conf:
        driver: local
        driver_opts:
            type: none
            o: bind
            device: etc/mariadb
    wordpress-conf:
        driver: local
        driver_opts:
            type: none
            o: bind
            device: etc/wordpress

services:
    mariadb:
        container_name: mariadb
        image: mariadb:genesis
        volumes:
            - mariadb:/var/lib/mysql
            - mariadb-conf:/etc/mysql
        build:
            context: mariadb
            args:
                - WP_DB_NAME=$WP_DB_NAME
                - WP_DB_USER=$WP_DB_USER
                - WP_DB_PASSWORD=$WP_DB_PASSWORD
                - MYSQL_ROOT_PASSWORD=$MYSQL_ROOT_PASSWORD
        restart: unless-stopped
        networks:
            - backend
    wordpress:
        container_name: wordpress
        image: wordpress:genesis
        volumes:
            - wordpress:/var/www/html/wp
            - wordpress-conf:/etc/wordpress
        build:
            context: wordpress
        environment:
            - DB_HOST=$WP_DB_HOST
            - DB_NAME=$WP_DB_NAME
            - DB_USER=$WP_DB_USER
            - DB_PASSWORD=$WP_DB_PASSWORD
        restart: unless-stopped
        depends_on:
            - mariadb
        networks:
            - backend
            - frontend
    nginx:
        container_name: nginx
        image: nginx:genesis
        volumes:
            - wordpress:/var/www/html/wp
        build: nginx
        ports:
            - 443:443
        restart: unless-stopped
        depends_on:
            - wordpress
        networks:
            - frontend
