networks:
    backend:
    frontend:

services:
    mariadb:
        image: mariadb:genesis
        build: ./requirements/mariadb
        container_name: mariadb
        restart: unless-stopped
        networks:
            - backend
    wordpress:
        image: wordpress:genesis
        build: ./requirements/wordpress
        container_name: wordpress
        restart: unless-stopped
        depends_on:
            - mariadb
        networks:
            - backend
            - frontend
    nginx:
        image: nginx:genesis
        build: ./requirements/nginx
        container_name: nginx
        ports:
            - 443:443
        restart: unless-stopped
        depends_on:
            - wordpress
        networks:
            - frontend
