services:
    nginx:
        image: nginx:inception
        build: ./requirements/nginx
        container_name: nginx
        ports:
            - 443:443
        restart: unless-stopped
    mariadb:
        image: mariadb:inception
        build: ./requirements/mariadb
        container_name: mariadb
        restart: unless-stopped
