services:
    mariadb:
        image: mariadb:genesis
        build: ./requirements/mariadb
        container_name: mariadb
        restart: unless-stopped
    wordpress:
        image: wordpress:genesis
        build: ./requirements/wordpress
        container_name: wordpress
        restart: unless-stopped
        depends_on:
            - mariadb
    nginx:
        image: nginx:genesis
        build: ./requirements/nginx
        container_name: nginx
        ports:
            - 443:443
        restart: unless-stopped
        depends_on:
            - wordpress
