version: "3.8"

networks:
    backend:
    frontend:

volumes:
    mariadb:
        driver: local
        driver_opts:
            type: none
            o: bind
            device: data/mariadb
    wordpress:
        driver: local
        driver_opts:
            type: none
            o: bind
            device: data/wordpress
    mariadb-conf:
        driver: local
        driver_opts:
            type: none
            o: bind
            device: mariadb/etc

services:
    mariadb:
        image: mariadb:genesis
        volumes:
            - mariadb:/var/lib/mysql
            - mariadb-conf:/etc/mysql
        build: mariadb
        container_name: mariadb
        restart: unless-stopped
        networks:
            - backend
    wordpress:
        image: wordpress:genesis
        volumes:
            - wordpress:/var/www/html/wp
        build: wordpress
        container_name: wordpress
        restart: unless-stopped
        depends_on:
            - mariadb
        networks:
            - backend
            - frontend
    nginx:
        image: nginx:genesis
        volumes:
            - wordpress:/var/www/html/wp
        build: nginx
        container_name: nginx
        ports:
            - 443:443
        restart: unless-stopped
        depends_on:
            - wordpress
        networks:
            - frontend
